language: node_js
node_js:
- '12'
cache:
  yarn: true
script:
- yarn lint
- yarn test
before_install:
- npm install -g yarn
- yarn install
notifications:
  email: false
  slack:
    secure: JXhMrtrvvrHWhSxZBcuwbiVtJ7gNisqrORrq6E90cPeLXDGhDQZy2tcVilWOGVhAaiNE4FGVclq7FAaBYJ+vaaI9+kitdQFca78eDLukd3fKyKpEarXrbogFMf7JAcZYp3CUsmQREic7XBMvFtl67A2Vr6ZZM3z7sMHcfKg62pIDSfAFWMthxEWDzadJSM+w1w4O/CFzHWjcwM8ijyPj9PfhF0jeS6dMbISI/hFod7tjX5ILqdyLU7iwGKvdbuoVZ4D++rsCGRACYxOcvCmpEnMIV4y4sv0hUwgvw+xxZvJhuTQK2qQ8YhIaxmW5sJZmGDDRxxOzLc308QnpTef8mKMaIxJX4j/efoUDIO/7QWqa8C7cZ2/qgYwDJWwj/omrfveZQnL9sRdjrkH1mjXEYG16lhe+owBOYaa4QhogF53GNuEI2uWz1EuZ5bZMRvrZmm6XSU2irIwLDmtDwAPk0diYc3l1EfRhqmITE8BLSsKoqGTPhYDo3SPqA9MKs03TeWh/2xE/iFaALUY780HKasQL9nlXi1L45C9XCX3YVHL3kCHxiSYMTct0V0xODdic6v2glRAZ1dEUzl4S+1dQzS7PqZ+GpZZclU/qp0lgQprCrUszXAOXIRFMh+qzRjAbfshyQwAOUKIHuRRNbViI7F32JT0g9oxMatFF5iGjcgs=
